name: status

on: [push]

jobs:

  lint-test:

    runs-on: ubuntu-latest

    container:
      image: analysiscenter1/ds-py3

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: Update pip
      run: pip3 install -U pip

    - name: Update pylint
      run: pip3 install -U pylint

    - name: Install requirements
      run: pip3 install -r requirements.txt

    - name: Check pylint
      run: pylint -rn --rcfile pylintrc src
